// flow-typed signature: af1ec441683129fd4ca760ef57f459dd
// flow-typed version: <<STUB>>/nervjs_v^1.2.15/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nervjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nervjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nervjs/dist/index.esm' {
  declare module.exports: any;
}

declare module 'nervjs/dist/index' {
  declare module.exports: any;
}

declare module 'nervjs/dist/index.prod' {
  declare module.exports: any;
}

declare module 'nervjs/dist/nerv' {
  declare module.exports: any;
}

declare module 'nervjs/dist/nerv.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nervjs/dist/index.esm.js' {
  declare module.exports: $Exports<'nervjs/dist/index.esm'>;
}
declare module 'nervjs/dist/index.js' {
  declare module.exports: $Exports<'nervjs/dist/index'>;
}
declare module 'nervjs/dist/index.prod.js' {
  declare module.exports: $Exports<'nervjs/dist/index.prod'>;
}
declare module 'nervjs/dist/nerv.js' {
  declare module.exports: $Exports<'nervjs/dist/nerv'>;
}
declare module 'nervjs/dist/nerv.min.js' {
  declare module.exports: $Exports<'nervjs/dist/nerv.min'>;
}
declare module 'nervjs/index' {
  declare module.exports: $Exports<'nervjs'>;
}
declare module 'nervjs/index.js' {
  declare module.exports: $Exports<'nervjs'>;
}
